-- Migrate Plan enum: FREE/PRO/ENTERPRISE -> TRIAL/STARTER/PROFESSIONAL/ENTERPRISE
ALTER TYPE "Plan" RENAME TO "Plan_old";

CREATE TYPE "Plan" AS ENUM ('TRIAL', 'STARTER', 'PROFESSIONAL', 'ENTERPRISE');

ALTER TABLE "Tenant" ADD COLUMN "plan_new" "Plan";

UPDATE "Tenant" SET "plan_new" = CASE "plan"::text
  WHEN 'FREE' THEN 'TRIAL'::"Plan"
  WHEN 'PRO' THEN 'PROFESSIONAL'::"Plan"
  WHEN 'ENTERPRISE' THEN 'ENTERPRISE'::"Plan"
  ELSE 'TRIAL'::"Plan"
END;

ALTER TABLE "Tenant" DROP COLUMN "plan";
ALTER TABLE "Tenant" RENAME COLUMN "plan_new" TO "plan";
ALTER TABLE "Tenant" ALTER COLUMN "plan" SET DEFAULT 'TRIAL'::"Plan";
ALTER TABLE "Tenant" ALTER COLUMN "plan" SET NOT NULL;

DROP TYPE "Plan_old";

ALTER TABLE "Tenant" ADD COLUMN "trialEndsAt" TIMESTAMP(3);
