import type { DecisionStatus, InvitationStatus } from "@prisma/client";

import { formatDateTime } from "@/lib/format";

import type { MinutesData, MinutesVoteResult } from "./types";

function esc(s: string | null | undefined): string {
  if (s == null) return "";
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/\n/g, "<br/>");
}

function decisionStatusLabel(status: DecisionStatus, locale: "ar" | "en"): string {
  const ar: Record<DecisionStatus, string> = {
    OPEN: "مفتوح",
    IN_PROGRESS: "قيد التنفيذ",
    DONE: "منجز",
    CANCELLED: "ملغي",
  };
  const en: Record<DecisionStatus, string> = {
    OPEN: "Open",
    IN_PROGRESS: "In progress",
    DONE: "Done",
    CANCELLED: "Cancelled",
  };
  return locale === "ar" ? ar[status] : en[status];
}

function rsvpLabel(s: InvitationStatus, locale: "ar" | "en"): string {
  const ar: Record<InvitationStatus, string> = {
    PENDING: "معلق",
    ACCEPTED: "مقبول",
    DECLINED: "مرفوض",
    TENTATIVE: "مبدئي",
  };
  const en: Record<InvitationStatus, string> = {
    PENDING: "Pending",
    ACCEPTED: "Accepted",
    DECLINED: "Declined",
    TENTATIVE: "Tentative",
  };
  return locale === "ar" ? ar[s] : en[s];
}

function voteResultLabel(r: MinutesVoteResult, locale: "ar" | "en"): string {
  if (locale === "ar") {
    if (r === "APPROVED") return "موافق";
    if (r === "REJECTED") return "مرفوض";
    return "تعادل";
  }
  if (r === "APPROVED") return "Approved";
  if (r === "REJECTED") return "Rejected";
  return "Tie";
}

export function generateMinutesHtml(
  data: MinutesData,
  locale: "ar" | "en",
): string {
  const dir = locale === "ar" ? "rtl" : "ltr";
  const font =
    locale === "ar"
      ? "'Cairo', 'Segoe UI', Tahoma, sans-serif"
      : "'Montserrat', 'Segoe UI', system-ui, sans-serif";

  const titleMain =
    locale === "ar"
      ? `محضر اجتماع — ${esc(data.meeting.typeLabel)}`
      : `Meeting Minutes — ${esc(data.meeting.typeLabel)}`;

  const generatedLine =
    locale === "ar"
      ? `أُنشئ بواسطة CCOS — ${formatDateTime(new Date(), locale)}`
      : `Generated by CCOS — ${formatDateTime(new Date(), locale)}`;

  const labels = {
    meetingInfo: locale === "ar" ? "بيانات الاجتماع" : "Meeting information",
    date: locale === "ar" ? "التاريخ" : "Date",
    start: locale === "ar" ? "وقت البدء" : "Start",
    end: locale === "ar" ? "وقت الانتهاء" : "End",
    duration: locale === "ar" ? "المدة" : "Duration",
    location: locale === "ar" ? "مكان الاجتماع" : "Venue",
    ccosLiveVenue: locale === "ar" ? "CCOS مباشر (داخل التطبيق)" : "CCOS Live (in-app)",
    objectives: locale === "ar" ? "الأهداف" : "Objectives",
    attendees: locale === "ar" ? "الحضور" : "Attendees",
    absentees: locale === "ar" ? "الغائبون" : "Absentees",
    agenda: locale === "ar" ? "جدول الأعمال" : "Agenda",
    decisionsSummary:
      locale === "ar" ? "ملخص القرارات" : "Decisions summary",
    votingSummary: locale === "ar" ? "نتائج التصويت" : "Voting results",
    question: locale === "ar" ? "السؤال" : "Question",
    approve: locale === "ar" ? "موافق" : "Approve",
    reject: locale === "ar" ? "مرفوض" : "Reject",
    abstain: locale === "ar" ? "ممتنع" : "Abstain",
    result: locale === "ar" ? "النتيجة" : "Result",
    signatures: locale === "ar" ? "التوقيعات" : "Signatures",
    none: locale === "ar" ? "—" : "—",
    notes: locale === "ar" ? "ملاحظات" : "Notes",
    createdBy: locale === "ar" ? "أنشئ بواسطة" : "Created by",
    status: locale === "ar" ? "الحالة" : "Status",
    owner: locale === "ar" ? "المسؤول" : "Owner",
    due: locale === "ar" ? "الاستحقاق" : "Due",
    checkedIn: locale === "ar" ? "حضور مسجّل" : "Checked in",
    rsvp: locale === "ar" ? "الرد" : "RSVP",
  };

  const m = data.meeting;
  const durationText = `${m.durationMin} ${locale === "ar" ? "دقيقة" : "min"}`;
  const loc = m.location?.trim() ?? "";
  const locationCell =
    loc && !/^https?:\/\//i.test(loc)
      ? esc(loc)
      : labels.ccosLiveVenue;

  const infoRows = [
    [labels.date, formatDateTime(m.scheduledAt, locale)],
    [
      labels.start,
      m.startedAt ? formatDateTime(m.startedAt, locale) : labels.none,
    ],
    [labels.end, m.endedAt ? formatDateTime(m.endedAt, locale) : labels.none],
    [labels.duration, durationText],
    [labels.location, locationCell],
    [
      labels.objectives,
      m.objectives?.trim() ? esc(m.objectives) : labels.none,
    ],
  ];

  const infoTable = `
    <table class="info-table" style="width:100%;border-collapse:collapse;margin:16px 0;font-size:13px;">
      <tbody>
        ${infoRows
          .map(
            ([k, v]) => `
          <tr>
            <td style="border:1px solid #ccc;padding:8px;width:28%;background:#f8f8f8;font-weight:600;">${k}</td>
            <td style="border:1px solid #ccc;padding:8px;">${v}</td>
          </tr>`,
          )
          .join("")}
      </tbody>
    </table>`;

  const attendeesHtml =
    data.attendees.length === 0
      ? `<p style="color:#666;">${labels.none}</p>`
      : `<ul style="margin:8px 0 16px 20px;padding:0;">
        ${data.attendees
          .map(
            (a) => `
          <li style="margin:4px 0;">
            <strong>${esc(a.name)}</strong> — ${esc(a.roleLabel)}
            <span style="color:#666;font-size:12px;">(${rsvpLabel(a.rsvpStatus, locale)}${
              a.checkedInAt
                ? ` · ${labels.checkedIn}: ${formatDateTime(a.checkedInAt, locale)}`
                : ""
            })</span>
          </li>`,
          )
          .join("")}
      </ul>`;

  const absenteesHtml =
    data.absentees.length === 0
      ? `<p style="color:#666;">${labels.none}</p>`
      : `<ul style="margin:8px 0 16px 20px;padding:0;">
        ${data.absentees
          .map(
            (a) => `
          <li style="margin:4px 0;"><strong>${esc(a.name)}</strong> — ${esc(
            a.roleLabel,
          )}</li>`,
          )
          .join("")}
      </ul>`;

  const agendaHtml = data.agenda
    .map((item) => {
      const title =
        locale === "en" && item.titleEn?.trim()
          ? esc(item.titleEn)
          : esc(item.titleAr);
      const decs =
        item.decisions.length === 0
          ? ""
          : `<div style="margin-top:8px;padding-inline-start:12px;border-inline-start:3px solid #ddd;">
          ${item.decisions
            .map(
              (d) => `
            <p style="margin:6px 0;font-size:13px;">
              <strong>${labels.status}:</strong> ${decisionStatusLabel(d.status, locale)} —
              ${esc(d.textAr)}
              ${d.textEn?.trim() ? `<br/><span style="color:#555">${esc(d.textEn)}</span>` : ""}
              <br/><span style="color:#888;font-size:12px;">${labels.createdBy}: ${esc(d.createdBy)}</span>
            </p>`,
            )
            .join("")}
        </div>`;

      const votes =
        item.votes.length === 0
          ? ""
          : `<div style="margin-top:8px;padding-inline-start:12px;border-inline-start:3px solid #bcd;">
          ${item.votes
            .map(
              (v) => `
            <p style="margin:6px 0;font-size:13px;">
              <strong>${esc(v.question)}</strong><br/>
              ${labels.approve}: ${v.tallies.approve} · ${labels.reject}: ${v.tallies.reject} · ${labels.abstain}: ${v.tallies.abstain}
              <br/><strong>${labels.result}:</strong> ${voteResultLabel(v.result, locale)}
            </p>`,
            )
            .join("")}
        </div>`;

      const notes = item.notes?.trim()
        ? `<p style="margin-top:6px;font-size:12px;color:#555;"><em>${labels.notes}:</em> ${esc(item.notes)}</p>`
        : "";

      return `
        <section style="margin-bottom:20px;padding-bottom:12px;border-bottom:1px solid #e5e5e5;">
          <h3 style="margin:0 0 8px;font-size:16px;">${item.order}. ${title}</h3>
          ${notes}
          ${decs}
          ${votes}
        </section>`;
    })
    .join("");

  const allDecisionsHtml =
    data.allDecisions.length === 0
      ? `<p style="color:#666;">${labels.none}</p>`
      : `<ol style="margin:8px 0 16px 20px;">
        ${data.allDecisions
          .map(
            (d) => `
          <li style="margin:8px 0;">
            <strong>#${d.number}</strong> — ${decisionStatusLabel(d.status, locale)}
            <div>${esc(d.textAr)}</div>
            ${d.textEn?.trim() ? `<div style="color:#555;">${esc(d.textEn)}</div>` : ""}
            <div style="font-size:12px;color:#888;">
              ${d.owner ? `${labels.owner}: ${esc(d.owner)} · ` : ""}
              ${d.dueDate ? `${labels.due}: ${formatDateTime(d.dueDate, locale)}` : ""}
            </div>
          </li>`,
          )
          .join("")}
      </ol>`;

  const votesTable =
    data.allVotes.length === 0
      ? `<p style="color:#666;">${labels.none}</p>`
      : `<table style="width:100%;border-collapse:collapse;font-size:13px;margin:12px 0;">
        <thead>
          <tr style="background:#f0f0f0;">
            <th style="border:1px solid #ccc;padding:8px;text-align:${locale === "ar" ? "right" : "left"};">${labels.question}</th>
            <th style="border:1px solid #ccc;padding:8px;">${labels.approve}</th>
            <th style="border:1px solid #ccc;padding:8px;">${labels.reject}</th>
            <th style="border:1px solid #ccc;padding:8px;">${labels.abstain}</th>
            <th style="border:1px solid #ccc;padding:8px;">${labels.result}</th>
          </tr>
        </thead>
        <tbody>
          ${data.allVotes
            .map(
              (v) => `
            <tr>
              <td style="border:1px solid #ccc;padding:8px;">${esc(v.question)}</td>
              <td style="border:1px solid #ccc;padding:8px;text-align:center;">${v.tallies.approve}</td>
              <td style="border:1px solid #ccc;padding:8px;text-align:center;">${v.tallies.reject}</td>
              <td style="border:1px solid #ccc;padding:8px;text-align:center;">${v.tallies.abstain}</td>
              <td style="border:1px solid #ccc;padding:8px;">${voteResultLabel(v.result, locale)}</td>
            </tr>`,
            )
            .join("")}
        </tbody>
      </table>`;

  const logoHtml = data.tenant.logo
    ? `<img src="${esc(data.tenant.logo)}" alt="" style="max-height:48px;max-width:160px;object-fit:contain;" />`
    : `<div style="font-weight:700;font-size:18px;">${esc(data.tenant.name)}</div>`;

  const signaturesHtml =
    data.signatures.length === 0
      ? `<p style="color:#666;font-size:13px;">${locale === "ar" ? "لا توقيعات بعد." : "No signatures yet."}</p>`
      : `<div style="display:flex;flex-wrap:wrap;gap:16px;margin-top:12px;">
        ${data.signatures
          .map(
            (s) => `
          <div style="border:1px solid #ccc;padding:12px;min-width:200px;flex:1 1 200px;">
            <div style="font-weight:600;">${esc(s.userName)}</div>
            <div style="font-size:12px;color:#666;">${esc(s.roleLabel)}</div>
            <div style="margin-top:8px;min-height:48px;border-bottom:1px solid #333;">
              ${
                s.signatureImageUrl
                  ? `<img src="${esc(s.signatureImageUrl)}" alt="" style="max-height:56px;max-width:100%;" />`
                  : s.typedName
                    ? `<span style="font-family:cursive;font-size:18px;">${esc(s.typedName)}</span>`
                    : "&nbsp;"
              }
            </div>
            <div style="font-size:11px;color:#888;margin-top:6px;">${formatDateTime(s.signedAt, locale)}</div>
          </div>`,
          )
          .join("")}
      </div>`;

  return `<div class="minutes-document" dir="${dir}" style="font-family:${font};font-size:14px;line-height:1.55;color:#111;max-width:900px;margin:0 auto;padding:24px;background:#fff;">
    <header style="display:flex;align-items:center;justify-content:space-between;gap:16px;border-bottom:2px solid #222;padding-bottom:16px;margin-bottom:16px;">
      <div>${logoHtml}</div>
      <div style="text-align:${locale === "ar" ? "left" : "right"};flex:1;">
        <h1 style="margin:0;font-size:22px;">${titleMain}</h1>
        <p style="margin:8px 0 0;font-size:16px;font-weight:600;">${esc(m.title)}</p>
      </div>
    </header>

    <h2 style="font-size:16px;margin:20px 0 8px;">${labels.meetingInfo}</h2>
    ${infoTable}

    <h2 style="font-size:16px;margin:20px 0 8px;">${labels.attendees}</h2>
    ${attendeesHtml}

    <h2 style="font-size:16px;margin:20px 0 8px;">${labels.absentees}</h2>
    ${absenteesHtml}

    <h2 style="font-size:16px;margin:20px 0 8px;">${labels.agenda}</h2>
    ${agendaHtml}

    <h2 style="font-size:16px;margin:20px 0 8px;">${labels.decisionsSummary}</h2>
    ${allDecisionsHtml}

    <h2 style="font-size:16px;margin:20px 0 8px;">${labels.votingSummary}</h2>
    ${votesTable}

    <h2 style="font-size:16px;margin:24px 0 8px;">${labels.signatures}</h2>
    ${signaturesHtml}

    <footer style="margin-top:32px;padding-top:12px;border-top:1px solid #ddd;font-size:11px;color:#888;text-align:center;">
      ${generatedLine}
    </footer>
  </div>`;
}
